export enum BlockchainNetwork {
  HYPERLEDGER_FABRIC = 'HYPERLEDGER_FABRIC',
  ETHEREUM_MAINNET = 'ETHEREUM_MAINNET',
  ETHEREUM_TESTNET = 'ETHEREUM_TESTNET',
  POLYGON = 'POLYGON',
  SOLANA = 'SOLANA',
}
